<a href="https://colab.research.google.com/github/Akash-Behera-123/Pytorch/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.11.0+cu128


In [2]:
if torch.cuda.is_available():
   print("GPU is available!")
   print(f"Using GPU:{torch.cuda.get_device_name(0)}")
else:
   print("GPU not available. Using  CPU.")

GPU is available!
Using GPU:Tesla T4


In [3]:
a=torch.empty(2,3)

In [4]:
type(a)

torch.Tensor

In [5]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.rand(2,3)

tensor([[0.7290, 0.3648, 0.1777],
        [0.6636, 0.6646, 0.7696]])

In [8]:
#manual seed

torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
#manual seed

torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
#using tensor
torch.tensor([[1,2,3],[3,4,5]])

tensor([[1, 2, 3],
        [3, 4, 5]])

In [11]:

print("using arange->", torch.arange(0,10,2))

print("using linspace->",torch.linspace(0,10,10))

print("using eye ->",torch.eye(5))

print("using full ->", torch.full((3,3),5))

using arange-> tensor([0, 2, 4, 6, 8])
using linspace-> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


#Tensor Shapes

In [12]:
x= torch.tensor([[1,2,3],[4,5,6]])

In [13]:
x.shape

torch.Size([2, 3])

In [14]:
torch.empty_like(x)

tensor([[    137107014139248,     137107014139248,               65536],
        [4681742012764214529,                  48,                  80]])

In [15]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [16]:
torch.rand_like(x,dtype=torch.float)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

#Tensor Datatype

In [17]:
x.dtype

torch.int64

In [18]:
#assign datatypes
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [19]:
torch.tensor([1.0,2.0,3.0],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [20]:
#using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [21]:
x.dtype

torch.int64

In [22]:
x= torch.rand(2,2)

In [23]:
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [24]:
#addition
x+2
#subtraction
x-4
#mul
x*5
#div
x/3
#int division
(x*100)//3
#mod
((x*100)//3)%2
#power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

In [25]:
c=torch.tensor([1,-2,3,-4])

In [26]:
#aabs
torch.abs(c)

tensor([1, 2, 3, 4])

In [27]:
#torch.round(d)

In [28]:
#torch.floor(d)

In [29]:
#clamp

#torch.clamp(d,min=2,max=3)

#Reduction operation

In [30]:
e= torch.randint(size=(2,3),low=0,high=10)
e

tensor([[1, 0, 4],
        [3, 8, 7]])

In [31]:
#sum
torch.sum(e)
#sum along column
torch.sum(e,dim=0)
#sum along rows
torch.sum(e,dim=1)

tensor([ 5, 18])

In [32]:
#means
#torch.mean(e) //flot only

In [33]:
#median
#torch.median()

In [34]:
#std deviation
# torch.std(e)

In [35]:
#variance
#torch.var(e)

In [36]:
#torch.argmax(e)

In [37]:
#torch.argmin(e)

In [38]:
#matrix multiplication
#torch.matmul(a,e)

In [40]:
vec1=torch.tensor([1,2])
vec2=torch.tensor([3,4])

#dot product
torch.dot(vec1,vec2)

tensor(11)

In [41]:
#transpose
#torch.transpose(f,0,1)

In [42]:
#determinant
#torch.det(h)

#Inplace Operations

In [43]:
m=torch.rand(2,3)
n=torch.rand(2,3)


print(m)
print(n)

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])
tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])


In [44]:
m.add_(n)

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])

In [45]:
m

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])

In [46]:
n

tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])

In [47]:
torch.relu(m)

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])

In [48]:
m.relu_()

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])

#Copying Operator

In [49]:
b=a.clone()

#Tensor Operation on GPU

In [51]:
torch.cuda.is_available()

True

In [52]:
device=torch.device('cuda')

In [54]:
#creating a new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.8344, 0.7001, 0.5361],
        [0.8883, 0.0220, 0.7938]], device='cuda:0')

In [55]:
#moving a existing tensor to GPU
a= torch.rand(2,3)
a

tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])

In [56]:
a.to(device)

tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]], device='cuda:0')

In [57]:
a+5

tensor([[5.0169, 5.2209, 5.9535],
        [5.7064, 5.1629, 5.8902]])

#Reshaping Tensor

In [58]:
a= torch.ones(4,4)

In [59]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [60]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [61]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [63]:
b= torch.rand(2,3,4)
b

tensor([[[0.5163, 0.0359, 0.6476, 0.3430],
         [0.3182, 0.5261, 0.0447, 0.5123],
         [0.9051, 0.5989, 0.4450, 0.7278]],

        [[0.4563, 0.3389, 0.6211, 0.5530],
         [0.6896, 0.3687, 0.9053, 0.8356],
         [0.3039, 0.6726, 0.5740, 0.9233]]])

In [64]:
#permute
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

#Numpy and Pytorch

In [65]:
import numpy as np

In [66]:
a= torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [67]:
b=a.numpy()

In [68]:
b

array([1, 2, 3])

In [69]:
type(b)

numpy.ndarray

In [70]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [71]:
torch.from_numpy(c)

tensor([1, 2, 3])